// LOCALHOST
###
GET http://localhost:8080/contacts
###
GET http://localhost:8080/contacts/6269c431fdd5c56c75afd024
###
GET http://localhost:8080/contacts/6269c493fdd5c56c75afd025
###
GET http://localhost:8080/contacts/6269c4c7fdd5c56c75afd026
###
POST http://localhost:8080/contacts HTTP/1.1
Content-Type: application/json

{
    "firstName": "joe",
    "lastName": "berry",
    "email": "joey.joe@gmail.com",
    "favoriteColor": "orange",
    "birthday": "020197"
}

###
PUT http://localhost:8080/contacts/6270106cf02a3913f4d0ca62 HTTP/1.1
Content-Type: application/json

{
    "firstName": "rasp",
    "lastName": "berry",
    "email": "berry.joe@gmail.com",
    "favoriteColor": "orange",
    "birthday": "020197"
}

###
DELETE http://localhost:8080/contacts/6270106df02a3913f4d0ca63 HTTP/1.1



// heroku
###
GET https://use-341-api.herokuapp.com/contacts
###
GET https://use-341-api.herokuapp.com/contacts/6269c431fdd5c56c75afd024
###
GET https://use-341-api.herokuapp.com/contacts/6269c493fdd5c56c75afd025
###
GET https://use-341-api.herokuapp.com/contacts/6269c4c7fdd5c56c75afd026
###

POST https://use-341-api.herokuapp.com/contacts HTTP/1.1
Content-Type: application/json

{
    "firstName": "josh",
    "lastName": "berry",
    "email": "joey.joe@gmail.com",
    "favoriteColor": "orange",
    "birthday": "020197"
}

###
PUT https://use-341-api.herokuapp.com/contacts/6270124b4b6271b6764be92b HTTP/1.1
Content-Type: application/json

{
    "firstName": "rasp",
    "lastName": "berry",
    "email": "berry.joe@gmail.com",
    "favoriteColor": "red",
    "birthday": "020197"
}

###
DELETE https://use-341-api.herokuapp.com/contacts/6279518b20dc267077aa93df HTTP/1.1